import {
  // System icons
  faPowerOff,
  faLock,
  faDesktop,
  faGear,
  faRotate,
  faDisplay,
  faKeyboard,
  faMouse,
  faHardDrive,
  faMemory,
  faMicrochip,
  faServer,
  faWifi,
  faNetworkWired,
  faBolt,
  faMoon,
  faSun,

  // Apps icons
  faGlobe,
  faTerminal,
  faFolder,
  faFolderOpen,
  faCalculator,
  faMusic,
  faImage,
  faVideo,
  faFile,
  faFileLines,
  faEnvelope,
  faCalendar,
  faCamera,
  faGamepad,
  faPaintbrush,
  faCode,

  // Media icons
  faPlay,
  faPause,
  faStop,
  faForward,
  faBackward,
  faVolumeHigh,
  faVolumeXmark,
  faVolumeLow,
  faMicrophone,
  faMicrophoneSlash,
  faHeadphones,
  faCirclePlay,
  faCirclePause,

  // Actions icons
  faDownload,
  faUpload,
  faLink,
  faTrash,
  faMagnifyingGlass,
  faPlus,
  faMinus,
  faXmark,
  faCheck,
  faPen,
  faCopy,
  faPaste,
  faScissors,
  faSave,
  faPrint,
  faShareNodes,

  // Files & Folders
  faFileCode,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFilePdf,
  faFileWord,
  faFileExcel,
  faFileZipper,
  faCloud,
  faCloudArrowDown,
  faCloudArrowUp,

  // Navigation
  faHome,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faBars,
  faEllipsisVertical,
  faGripVertical,

  // Communication
  faComment,
  faComments,
  faBell,
  faPhone,
  faVideo as faVideoCamera,

  // Misc
  faStar,
  faHeart,
  faFlag,
  faClock,
  faLocationDot,
  faGift,
  faLightbulb,
  faWrench,
  faSliders,
  faBug,
  faShieldHalved,
} from '@fortawesome/free-solid-svg-icons';

export const ICON_CATEGORIES = {
  system: {
    label: 'System',
    icons: [
      { name: 'faPowerOff', icon: faPowerOff, label: 'Power' },
      { name: 'faLock', icon: faLock, label: 'Lock' },
      { name: 'faDesktop', icon: faDesktop, label: 'Desktop' },
      { name: 'faDisplay', icon: faDisplay, label: 'Display' },
      { name: 'faGear', icon: faGear, label: 'Settings' },
      { name: 'faRotate', icon: faRotate, label: 'Refresh' },
      { name: 'faKeyboard', icon: faKeyboard, label: 'Keyboard' },
      { name: 'faMouse', icon: faMouse, label: 'Mouse' },
      { name: 'faHardDrive', icon: faHardDrive, label: 'Hard Drive' },
      { name: 'faMemory', icon: faMemory, label: 'Memory' },
      { name: 'faMicrochip', icon: faMicrochip, label: 'CPU' },
      { name: 'faServer', icon: faServer, label: 'Server' },
      { name: 'faWifi', icon: faWifi, label: 'WiFi' },
      { name: 'faNetworkWired', icon: faNetworkWired, label: 'Network' },
      { name: 'faBolt', icon: faBolt, label: 'Power' },
      { name: 'faMoon', icon: faMoon, label: 'Night Mode' },
      { name: 'faSun', icon: faSun, label: 'Day Mode' },
    ],
  },
  apps: {
    label: 'Apps',
    icons: [
      { name: 'faGlobe', icon: faGlobe, label: 'Browser' },
      { name: 'faTerminal', icon: faTerminal, label: 'Terminal' },
      { name: 'faFolder', icon: faFolder, label: 'Folder' },
      { name: 'faFolderOpen', icon: faFolderOpen, label: 'Open Folder' },
      { name: 'faCalculator', icon: faCalculator, label: 'Calculator' },
      { name: 'faMusic', icon: faMusic, label: 'Music' },
      { name: 'faImage', icon: faImage, label: 'Image' },
      { name: 'faVideo', icon: faVideo, label: 'Video' },
      { name: 'faFile', icon: faFile, label: 'File' },
      { name: 'faFileLines', icon: faFileLines, label: 'Document' },
      { name: 'faEnvelope', icon: faEnvelope, label: 'Mail' },
      { name: 'faCalendar', icon: faCalendar, label: 'Calendar' },
      { name: 'faCamera', icon: faCamera, label: 'Camera' },
      { name: 'faGamepad', icon: faGamepad, label: 'Games' },
      { name: 'faPaintbrush', icon: faPaintbrush, label: 'Paint' },
      { name: 'faCode', icon: faCode, label: 'Code Editor' },
    ],
  },
  media: {
    label: 'Media',
    icons: [
      { name: 'faPlay', icon: faPlay, label: 'Play' },
      { name: 'faPause', icon: faPause, label: 'Pause' },
      { name: 'faStop', icon: faStop, label: 'Stop' },
      { name: 'faForward', icon: faForward, label: 'Forward' },
      { name: 'faBackward', icon: faBackward, label: 'Backward' },
      { name: 'faCirclePlay', icon: faCirclePlay, label: 'Play Circle' },
      { name: 'faCirclePause', icon: faCirclePause, label: 'Pause Circle' },
      { name: 'faVolumeHigh', icon: faVolumeHigh, label: 'Volume Up' },
      { name: 'faVolumeLow', icon: faVolumeLow, label: 'Volume Down' },
      { name: 'faVolumeXmark', icon: faVolumeXmark, label: 'Mute' },
      { name: 'faMicrophone', icon: faMicrophone, label: 'Microphone' },
      { name: 'faMicrophoneSlash', icon: faMicrophoneSlash, label: 'Mic Mute' },
      { name: 'faHeadphones', icon: faHeadphones, label: 'Headphones' },
    ],
  },
  files: {
    label: 'Files',
    icons: [
      { name: 'faFileCode', icon: faFileCode, label: 'Code File' },
      { name: 'faFileImage', icon: faFileImage, label: 'Image File' },
      { name: 'faFileVideo', icon: faFileVideo, label: 'Video File' },
      { name: 'faFileAudio', icon: faFileAudio, label: 'Audio File' },
      { name: 'faFilePdf', icon: faFilePdf, label: 'PDF' },
      { name: 'faFileWord', icon: faFileWord, label: 'Word Doc' },
      { name: 'faFileExcel', icon: faFileExcel, label: 'Excel' },
      { name: 'faFileZipper', icon: faFileZipper, label: 'Archive' },
      { name: 'faCloud', icon: faCloud, label: 'Cloud' },
      { name: 'faCloudArrowDown', icon: faCloudArrowDown, label: 'Download Cloud' },
      { name: 'faCloudArrowUp', icon: faCloudArrowUp, label: 'Upload Cloud' },
    ],
  },
  actions: {
    label: 'Actions',
    icons: [
      { name: 'faDownload', icon: faDownload, label: 'Download' },
      { name: 'faUpload', icon: faUpload, label: 'Upload' },
      { name: 'faLink', icon: faLink, label: 'Link' },
      { name: 'faTrash', icon: faTrash, label: 'Delete' },
      { name: 'faMagnifyingGlass', icon: faMagnifyingGlass, label: 'Search' },
      { name: 'faPlus', icon: faPlus, label: 'Add' },
      { name: 'faMinus', icon: faMinus, label: 'Remove' },
      { name: 'faXmark', icon: faXmark, label: 'Close' },
      { name: 'faCheck', icon: faCheck, label: 'Confirm' },
      { name: 'faPen', icon: faPen, label: 'Edit' },
      { name: 'faCopy', icon: faCopy, label: 'Copy' },
      { name: 'faPaste', icon: faPaste, label: 'Paste' },
      { name: 'faScissors', icon: faScissors, label: 'Cut' },
      { name: 'faSave', icon: faSave, label: 'Save' },
      { name: 'faPrint', icon: faPrint, label: 'Print' },
      { name: 'faShareNodes', icon: faShareNodes, label: 'Share' },
    ],
  },
  communication: {
    label: 'Communication',
    icons: [
      { name: 'faComment', icon: faComment, label: 'Comment' },
      { name: 'faComments', icon: faComments, label: 'Chat' },
      { name: 'faBell', icon: faBell, label: 'Notifications' },
      { name: 'faPhone', icon: faPhone, label: 'Phone' },
      { name: 'faEnvelope', icon: faEnvelope, label: 'Email' },
    ],
  },
  misc: {
    label: 'Misc',
    icons: [
      { name: 'faHome', icon: faHome, label: 'Home' },
      { name: 'faStar', icon: faStar, label: 'Star' },
      { name: 'faHeart', icon: faHeart, label: 'Heart' },
      { name: 'faFlag', icon: faFlag, label: 'Flag' },
      { name: 'faClock', icon: faClock, label: 'Clock' },
      { name: 'faLocationDot', icon: faLocationDot, label: 'Location' },
      { name: 'faGift', icon: faGift, label: 'Gift' },
      { name: 'faLightbulb', icon: faLightbulb, label: 'Idea' },
      { name: 'faWrench', icon: faWrench, label: 'Tools' },
      { name: 'faSliders', icon: faSliders, label: 'Adjust' },
      { name: 'faBug', icon: faBug, label: 'Bug' },
      { name: 'faShieldHalved', icon: faShieldHalved, label: 'Security' },
      { name: 'faBars', icon: faBars, label: 'Menu' },
      { name: 'faArrowLeft', icon: faArrowLeft, label: 'Back' },
      { name: 'faArrowRight', icon: faArrowRight, label: 'Forward' },
      { name: 'faArrowUp', icon: faArrowUp, label: 'Up' },
      { name: 'faArrowDown', icon: faArrowDown, label: 'Down' },
    ],
  },
};

// Flatten all icons for search functionality
export const ALL_ICONS = Object.values(ICON_CATEGORIES).flatMap(category =>
  category.icons.map(icon => ({
    ...icon,
    category: category.label,
  }))
);

// Quick access to commonly used icons
export const POPULAR_ICONS = [
  { name: 'faGlobe', icon: faGlobe, label: 'Browser' },
  { name: 'faTerminal', icon: faTerminal, label: 'Terminal' },
  { name: 'faFolder', icon: faFolder, label: 'Folder' },
  { name: 'faCalculator', icon: faCalculator, label: 'Calculator' },
  { name: 'faMusic', icon: faMusic, label: 'Music' },
  { name: 'faGear', icon: faGear, label: 'Settings' },
  { name: 'faPowerOff', icon: faPowerOff, label: 'Power' },
  { name: 'faVolumeHigh', icon: faVolumeHigh, label: 'Volume' },
];
